#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
umask 077
[[ -t 0 ]] || { echo 'Run this wizard in your own terminal.' >&2; exit 1; }
root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
ENV_FILE="$HOME/.config/orchestration-kit/setup.env"
mkdir -p "$(dirname "$ENV_FILE")"

hogli() { (cd "$POSTHOG_DIR" && flox activate -- ./bin/hogli "$@"); }
remote() {
  local tty="$1" command
  shift
  printf -v command '%q ' "$@"
  ssh "$tty" "$SSH_HOST" "bash -lc $(printf '%q' "$command")"
}

banner "Set up an orchestration devbox"
say "1. Sign in to Coder. 2. Choose and start a box. 3. Choose its schedule."
say "4. Install the kit. 5. Sign in to Claude. 6. Register and verify the project."
say "7. Pair T3 and check a remote session."
pause "Press Enter to use these stages, or Ctrl-C to stop."

stage "Sign in to Coder"
say "Connect this workstation to the PostHog Tailscale network first."
open_url "https://coder.dev.posthog.dev"
ask POSTHOG_DIR "Path to your local PostHog checkout:"
case "$POSTHOG_DIR" in '~') POSTHOG_DIR="$HOME" ;; '~/'*) POSTHOG_DIR="$HOME/${POSTHOG_DIR#\~/}" ;; esac
[[ -f "$POSTHOG_DIR/bin/hogli" ]] || { say 'That checkout has no bin/hogli.'; exit 1; }
POSTHOG_DIR=$(cd "$POSTHOG_DIR" && pwd -P)
command -v flox >/dev/null || { say 'Install Flox from https://flox.dev/docs/install-flox/ and rerun.'; exit 1; }
write_env POSTHOG_DIR "$POSTHOG_DIR"
say "Coder's setup command will show a sign-in link when needed."
hogli devbox:setup --configure-ssh --skip-configure-git-identity \
  --skip-configure-git-signing --skip-configure-region \
  --skip-configure-dotfiles --skip-configure-claude
hogli devbox:doctor

stage "Choose and start a box"
hogli devbox:list
say "Pick a new label for a separate box, or the label of your existing box."
ask BOX_LABEL "Box label [design]:"
BOX_LABEL=${BOX_LABEL:-design}
[[ "$BOX_LABEL" =~ ^[a-z0-9][a-z0-9-]*$ ]] || { say 'Use lowercase letters, numbers, and hyphens.'; exit 1; }
ask REGION "Region [us-east-1]:"
REGION=${REGION:-us-east-1}
case "$REGION" in us-east-1|eu-central-1) ;; *) say 'Choose us-east-1 or eu-central-1.'; exit 1 ;; esac
ask DISK "Disk GiB [200]:"
DISK=${DISK:-200}
case "$DISK" in 100|200) ;; *) say 'Choose 100 or 200 GiB.'; exit 1 ;; esac
say "A new box uses the chosen region and disk. Existing boxes keep theirs."
confirm "Start or create this box under your Coder account?" || exit 1
hogli devbox:start "$BOX_LABEL" --region "$REGION" --disk "$DISK" --no-start-app
hogli devbox:list
ask BOX_NAME "Exact workspace name from that list (devbox-...):"
[[ "$BOX_NAME" =~ ^devbox-[a-zA-Z0-9][a-zA-Z0-9-]*$ ]] || { say 'Enter the exact devbox name.'; exit 1; }
SSH_HOST="coder.$BOX_NAME"
remote -T true
write_env BOX_LABEL "$BOX_LABEL"
write_env REGION "$REGION"
write_env DISK "$DISK"
write_env BOX_NAME "$BOX_NAME"

stage "Choose the keep-running schedule"
say "Turning off automatic stop keeps long runs alive and incurs compute cost."
say "Template limits still apply. You can stop the box yourself when done."
if confirm "Disable automatic stop and start this box daily at 06:00 UTC?"; then
  "$HOME/.hogli/bin/coder" schedule stop "$BOX_NAME" manual
  "$HOME/.hogli/bin/coder" schedule start "$BOX_NAME" 06:00 UTC
else
  warn "Your existing stop schedule can interrupt a long run."
fi
"$HOME/.hogli/bin/coder" schedule show "$BOX_NAME"
pause "Press Enter after checking the schedule."

stage "Install the portable kit"
say "Preview the home-directory links before installing. Existing files stay intact."
kit_id=$(cat "$root/KIT_ID")
if remote -T bash -c 'test -e "$HOME/dev/orchestration-kit" || test -L "$HOME/dev/orchestration-kit"'; then
  remote -T bash -c 'test ! -L "$HOME/dev/orchestration-kit" && test "$(cat "$HOME/dev/orchestration-kit/KIT_ID")" = "$1"' kit "$kit_id" || {
    say 'The box already has a different kit or an unmanaged directory. Keep it and inspect it before retrying.'
    exit 1
  }
else
  tar -C "$root" -czf - . | remote -T bash -c 'set -eu
    mkdir -p "$HOME/dev"
    work=$(mktemp -d "$HOME/dev/.orchestration-kit.XXXXXX")
    trap '\''rm -rf "$work"'\'' EXIT
    tar -xzf - -C "$work"
    mv -T -n "$work" "$HOME/dev/orchestration-kit"
    [ ! -d "$work" ] || { echo "Keep existing orchestration-kit directory." >&2; exit 1; }'
fi
remote -T bash -c 'sh "$HOME/dev/orchestration-kit/install.sh" plan'
remote -T bash -c 'sh "$HOME/dev/orchestration-kit/scripts/t3-headless.sh" plan; sh "$HOME/dev/orchestration-kit/scripts/tailscale-routes.sh" plan'
say "The runtime also adds the systemd session environment to your Bash login files."
confirm "Apply these links and install the devbox runtime?" || exit 1
remote -T bash -c 'bash "$HOME/dev/orchestration-kit/scripts/setup-box.sh" prepare'
say "Use the login link from the next command if Tailscale needs sign-in."
remote -t bash -c 'sudo tailscale up --operator="$(id -un)" --accept-routes=false'

stage "Sign in to Claude on the box"
say "Sign in through Claude's own browser flow. The kit never copies your token."
remote -t bash -c 'command -v claude >/dev/null || { echo "Claude is missing from this template. Install it from https://code.claude.com/docs/en/setup, then rerun."; exit 1; }; env -u CLAUDE_CODE_OAUTH_TOKEN -u ANTHROPIC_API_KEY -u ANTHROPIC_AUTH_TOKEN claude auth status >/dev/null 2>&1 || env -u CLAUDE_CODE_OAUTH_TOKEN -u ANTHROPIC_API_KEY -u ANTHROPIC_AUTH_TOKEN claude auth login'

stage "Choose the code and issue repositories"
ask REPO_URL "Project clone URL (https://github.com/owner/repo.git or git@github.com:owner/repo.git):"
[[ "$REPO_URL" =~ ^(https://github\.com/|git@github\.com:)[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$ ]] || { say 'Use a GitHub HTTPS or SSH clone URL.'; exit 1; }
write_env REPO_URL "$REPO_URL"
say "The box clones this repository into ~/dev/design-project. Your existing Git identity stays."
warn "Orchestration creates many issues. Do not use the public PostHog/posthog repo for design tickets."
say "Choose a dedicated issue repository you own, preferably private. This is separate from the code clone."
say "If you need a repository, create it on GitHub with Issues enabled."
open_url "https://github.com/new"
ask ISSUE_REPO "GitHub issue repository (owner/repo):"
ISSUE_REPO=$(sh "$root/scripts/configure-issue-repo.sh" validate "$ISSUE_REPO")
remote -T bash -c 'set -euo pipefail
  gh repo view "$1" --json nameWithOwner,visibility,hasIssuesEnabled,viewerPermission | python3 -c '\''import json,sys
repo=json.load(sys.stdin)
if not repo["hasIssuesEnabled"]:
    sys.exit("Enable Issues on the selected repository, then rerun the wizard.")
if repo["viewerPermission"] not in ["ADMIN", "MAINTAIN", "WRITE", "TRIAGE"]:
    sys.exit("Choose an issue repository you can manage, preferably your own private repo.")
print(repo["nameWithOwner"] + " (" + repo["visibility"] + "): issues enabled and writable.")'\''' kit "$ISSUE_REPO"
write_env ISSUE_REPO "$ISSUE_REPO"
remote -T bash -c 'bash "$HOME/dev/orchestration-kit/scripts/setup-box.sh" finish "$1" "$2"' kit "$REPO_URL" "$ISSUE_REPO"

stage "Pair T3 and check a remote session"
open_url "https://t3.codes"
say "Open T3. In Settings, Connections, choose Add environment."
say "Use the link printed below within 30 minutes. It works once. Keep it private."
remote -T t3 pair --tailscale --tailscale-serve-port 60001 --ttl 30m --label Desktop
step "Paste the link into Add environment and select the remote environment."
step "Open design-project. Start a Claude thread asking it to print hostname and pwd."
step "Confirm it names your box and ~/dev/design-project."
confirm "Did that remote Claude thread complete on the expected box and project?" || {
  say 'Setup is not verified yet. Check README.md, then rerun this wizard.'
  exit 1
}
finish
say "Use the design-session prompt in README.md with your goal document."
say "To stop compute later: hogli devbox:stop $BOX_LABEL"
